### ISSUE TITLE
Help, the mod is not working.

### ISSUE THREAD

**Issue by Shark10199** [Stereowalker/Reforged#62]
[18:17:35] [main/INFO]: ModLauncher running: args [--username, JackFrostblade, --version, 1.20.1, --gameDir, C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures, --assetsDir, C:\Users\jacob\AppData\Roaming\ATLauncher\assets, --assetIndex, 5, --uuid, b11c51eabf2e4505a849f0448840a994, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.1, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --width=854, --height=480]
[18:17:35] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.3 by Microsoft; OS Windows 11 arch amd64 version 10.0
[18:17:35] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[18:17:35] [main/INFO]: Trying GL version 4.6
[18:17:35] [main/INFO]: Requested GL version 4.6 got version 4.6
[18:17:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/jacob/AppData/Roaming/ATLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT
[18:17:36] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.99, NVIDIA Corporation
[18:17:36] [main/INFO]: Found mod file AttributeFix-Forge-1.20.1-21.0.2.jar of type MOD with provider {mods folder locator at C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\mods}
[18:17:36] [main/INFO]: Found mod file AutoLeveling-1.20-1.18.jar of type MOD with provider {mods folder locator at C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\mods}
[18:17:36] [main/INFO]: Found mod file curios-forge-5.3.5+1.20.1.jar of type MOD with provider {mods folder locator at C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\mods}
[18:17:36] [main/INFO]: Found mod file MaxHealthFix-Forge-1.20.1-12.0.2.jar of type MOD with provider {mods folder locator at C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\mods}
[18:17:36] [main/INFO]: Found mod file PassiveSkillTree-1.20.1-BETA-0.5.8.jar of type MOD with provider {mods folder locator at C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\mods}
[18:17:36] [main/INFO]: Found mod file Tiered-1.20.1-6.0.2-Forge.jar of type MOD with provider {mods folder locator at C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\mods}
[18:17:36] [main/INFO]: Found mod file UnionLib-1.20.1-10.2.1-Forge.jar of type MOD with provider {mods folder locator at C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\mods}
[18:17:36] [main/WARN]: Mod file C:\Users\jacob\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.1\fmlcore-1.20.1-47.2.1.jar is missing mods.toml file
[18:17:36] [main/WARN]: Mod file C:\Users\jacob\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.1\javafmllanguage-1.20.1-47.2.1.jar is missing mods.toml file
[18:17:36] [main/WARN]: Mod file C:\Users\jacob\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.1\lowcodelanguage-1.20.1-47.2.1.jar is missing mods.toml file
[18:17:36] [main/WARN]: Mod file C:\Users\jacob\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.1\mclanguage-1.20.1-47.2.1.jar is missing mods.toml file
[18:17:36] [main/INFO]: Found mod file fmlcore-1.20.1-47.2.1.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659a2455
[18:17:36] [main/INFO]: Found mod file javafmllanguage-1.20.1-47.2.1.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659a2455
[18:17:36] [main/INFO]: Found mod file lowcodelanguage-1.20.1-47.2.1.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659a2455
[18:17:36] [main/INFO]: Found mod file mclanguage-1.20.1-47.2.1.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659a2455
[18:17:36] [main/INFO]: Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659a2455
[18:17:36] [main/INFO]: Found mod file forge-1.20.1-47.2.1-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@659a2455
[18:17:36] [main/INFO]: No dependencies to load found. Skipping!
[18:17:37] [main/INFO]: Compatibility level set to JAVA_17
[18:17:37] [main/ERROR]: Mixin config tiered.mixins.json does not specify "minVersion" property
[18:17:37] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures, --assetsDir, C:\Users\jacob\AppData\Roaming\ATLauncher\assets, --uuid, b11c51eabf2e4505a849f0448840a994, --username, JackFrostblade, --assetIndex, 5, --accessToken, ????????, --userType, msa, --versionType, release, --width=854, --height=480]
[18:17:37] [main/WARN]: Error loading class: fuzs/easymagic/world/inventory/ModEnchantmentMenu (java.lang.ClassNotFoundException: fuzs.easymagic.world.inventory.ModEnchantmentMenu)
[18:17:37] [main/WARN]: @Mixin target fuzs.easymagic.world.inventory.ModEnchantmentMenu was not found skilltree.mixins.json:easymagic/MixinModEnchantmentMenu
[18:17:37] [main/WARN]: Error loading class: vectorwing/farmersdelight/common/block/entity/CookingPotBlockEntity (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity)
[18:17:37] [main/WARN]: @Mixin target vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity was not found skilltree.mixins.json:farmersdelight/MixinCookingPotBlockEntity
[18:17:37] [main/WARN]: Error loading class: vectorwing/farmersdelight/common/block/entity/StoveBlockEntity (java.lang.ClassNotFoundException: vectorwing.farmersdelight.common.block.entity.StoveBlockEntity)
[18:17:37] [main/WARN]: @Mixin target vectorwing.farmersdelight.common.block.entity.StoveBlockEntity was not found skilltree.mixins.json:farmersdelight/MixinStoveBlockEntity
[18:17:40] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 95 milliseconds
[18:17:41] [Render thread/WARN]: Assets URL 'union:/C:/Users/jacob/AppData/Roaming/ATLauncher/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23170!/assets/.mcassetsroot' uses unexpected schema
[18:17:41] [Render thread/WARN]: Assets URL 'union:/C:/Users/jacob/AppData/Roaming/ATLauncher/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23170!/data/.mcassetsroot' uses unexpected schema
[18:17:41] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:17:42] [Render thread/INFO]: Setting user: JackFrostblade
[18:17:42] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[18:17:42] [modloading-worker-0/INFO]: Loaded maxhealthfix for Forge.
[18:17:42] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: tiered, class com.stereowalker.tiered.Tiered
java.lang.NoClassDefFoundError: com/stereowalker/unionlib/insert/handler/LivingInsertHandler
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23172!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23171!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.stereowalker.unionlib.insert.handler.LivingInsertHandler
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[18:17:42] [modloading-worker-0/INFO]: Forge mod loading, version 47.2.1, for MC 1.20.1 with MCP 20230612.114412
[18:17:42] [modloading-worker-0/INFO]: MinecraftForge v47.2.1 Initialized
[18:17:42] [modloading-worker-0/INFO]: Starting up: unionlib
[18:17:42] [Render thread/FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterParticleProvidersEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterTextureAtlasSpriteLoadersEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterKeyMappingsEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterGuiOverlaysEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$ColorResolvers to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterItemDecorationsEvent to a broken mod state
[18:17:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterPresetEditorsEvent to a broken mod state
[18:17:43] [Render thread/INFO]: Reloading ResourceManager: vanilla
[18:17:43] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state
[18:17:43] [Worker-Main-13/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[18:17:43] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state
[18:17:44] [Worker-Main-9/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$ModifyBakingResult to a broken mod state
[18:17:44] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[18:17:44] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18:17:45] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[18:17:45] [Render thread/INFO]: Sound engine started
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$BakingCompleted to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[18:17:45] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:17:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[18:17:45] [Render thread/FATAL]: Preparing crash report with UUID 6bf1963c-695f-4de0-a615-fc7b8c487630
[18:17:45] [Render thread/FATAL]: Crash report saved to C:\Users\jacob\AppData\Roaming\ATLauncher\instances\SkillCraftAdventures\crash-reports\crash-2023-10-07_18.17.45-fml.txt
[18:17:45] [Render thread/FATAL]: Preparing crash report with UUID ce2aa45d-0eaa-4553-8d93-c82eed100284
[18:17:45] [Render thread/INFO]: Initializing mod on client: unionlib
[18:17:45] [Render thread/INFO]: Not registering unionlib's Clientbound packets Because This: -> BOTH Game: -> ONLY_UNIONLIB

**Comment by Stereowalker** [comment]
Are you still having this issue with the new release?
