### ISSUE TITLE
Joining world crash Forge 1.20.1 (Better Combat compat?)

### ISSUE THREAD

**Issue by abby-cadabra** [Stereowalker/Reforged#73]
Hiya,

Having a crash on world load with Tiered 6.0.4 and UnionLib 10.2.5. World loads normally when Tiered and Union are unticked.

Crash log suggests a problem with Better Combat:

19:53:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "attributeId" is null
	at net.bettercombat.logic.WeaponAttributesFallback.hasAttributeModifier(WeaponAttributesFallback.java:53) ~[bettercombat-forge-1.8.5+1.20.1.jar%23521!/:?]
	at net.bettercombat.logic.WeaponAttributesFallback.initialize(WeaponAttributesFallback.java:24) ~[bettercombat-forge-1.8.5+1.20.1.jar%23521!/:?]
	at net.bettercombat.BetterCombat.lambda$onInitialize$0(BetterCombat.java:43) ~[bettercombat-forge-1.8.5+1.20.1.jar%23521!/:?]
	at net.bettercombat.forge.events.ForgeEvents.lambda$onSererStart$2(ForgeEvents.java:31) ~[bettercombat-forge-1.8.5+1.20.1.jar%23521!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.bettercombat.forge.events.ForgeEvents.onSererStart(ForgeEvents.java:31) ~[bettercombat-forge-1.8.5+1.20.1.jar%23521!/:?]
	at net.bettercombat.forge.events.__ForgeEvents_onSererStart_ServerStartedEvent.invoke(.dynamic) ~[bettercombat-forge-1.8.5+1.20.1.jar%23521!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:115) ~[forge-1.20.1-47.2.20-universal.jar%23817!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:638) ~[client-1.20.1-20230612.114412-srg.jar%23812!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23812!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

Happy to provide any further info. 

[crash-2024-05-13_19.53.20-server.txt](https://github.com/Stereowalker/tiered/files/15292744/crash-2024-05-13_19.53.20-server.txt)

**Comment by VinterNacht** [comment]
I came here to follow up on this exact error. Mine occurred in combination with the Tiered (Forge) Mod, and it looks like yours did as well.

**Comment by abby-cadabra** [comment]
I never found any solution or got any follow-up on it, so I'm guessing it's just going to be a "pick which mod you want more" situation. Not sure that this mod is being maintained anymore.

**Comment by VinterNacht** [comment]
That would be most unfortunate since there isn't an alternative for it out there.
