### ISSUE TITLE
Not working on server buckets.

### ISSUE THREAD

**Issue by pil0lo** [Stereowalker/Reforged#93]
I open a server with a server bucket and play with my friends.
When I put this mod in and start the server, the server won't open.
Why is that???

UnionLib-1.21-12.0.3-Fabric
Fabric-API-1.21
Reforged-1.21-1.0.1-Fabric
Even if I just put this in, the server won't open.

I get various errors, but the server opens. If I just put in this mode, the server won't open.

00:30:34 | Failed to start the minecraft serverjava.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tiered'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayPayloadHandler in environment type SERVER
	at com.stereowalker.unionlib.fabric.FabricMod$2.registerClientboundPacket(FabricMod.java:111) ~[UnionLib-1.21-12.0.3-Fabric.jar:?]
	at com.stereowalker.tiered.Reforged.registerPackets(Reforged.java:296) ~[Reforged-1.21-1.0.1-Fabric.jar:?]
	at com.stereowalker.unionlib.fabric.FabricMod.onInitialize(FabricMod.java:100) ~[UnionLib-1.21-12.0.3-Fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking$PlayPayloadHandler in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.stereowalker.unionlib.fabric.FabricMod$2.registerClientboundPacket(FabricMod.java:111) ~[UnionLib-1.21-12.0.3-Fabric.jar:?]
	at com.stereowalker.tiered.Reforged.registerPackets(Reforged.java:296) ~[Reforged-1.21-1.0.1-Fabric.jar:?]
	at com.stereowalker.unionlib.fabric.FabricMod.onInitialize(FabricMod.java:100) ~[UnionLib-1.21-12.0.3-Fabric.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more

**Comment by AuKay** [comment]
I have the same exact problem on G-portal

**Comment by pil0lo** [comment]
Is the server not opening because G-Portal is a mode issue??
Among the modes I put in, the portal is cryportals-1.21.0-2.7 This mode.

List of modes.
![Screenshot_20240729_060259_DS file](https://github.com/user-attachments/assets/43c58f0f-591f-467d-8ae0-adb43a3529f2)
